server:
  port: 8081

spring:
  redis:
    database: 0           # 数据库名db0
    host: 192.168.85.150  # 服务器地址
    port: 6379            # 端口
    lettuce:              # SpringBoot2.0之后默认使用lettuce该客户端连接Redis服务器
      pool:               # 配置连接池
        max-idle: 8       # 连接池的最大连接数
        min-idle: 0       # 连接池的最小连接数
        max-active: 8     # 在给定时间连接池可以分配的最大连接数
        max-wait: -1      # 当池被耗尽时，抛出异常之前连接分配应该阻塞的最大时间量（单位：ms）值为负时表示无限期阻止
    timeout: 5000         # 连接超时时间

